name: Auto PR from Dev to Main

on:
  push:
    branches:
      - dev

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: dev
          destination_branch: main
          pr_title: "PR automático de push"
          pr_body: "."
          pr_draft: false
          github_token: ${{ secrets.token }}
